app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    hostNetwork: false
  controllers:
    main:
      pod:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 1000
      containers:
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: latest
            pullPolicy: IfNotPresent
          env:
            DOT: "off"
            DNS_KEEP_NAMESERVER: "on"
            DNS_ADDRESS: "103.86.96.100"
            TZ: "America/New_York"
            VPN_SERVICE_PROVIDER: nordvpn
            VPN_TYPE: openvpn
            OPENVPN_USER:
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: username
            OPENVPN_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: password
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
        main:
          dependsOn: gluetun  # QBittorrent depends on Gluetun being ready
          image:
            repository: qbittorrentofficial/qbittorrent-nox
            tag: latest
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            QBT_LEGAL_NOTICE: "confirm"
            QBT_TORRENTING_PORT: "6881"
            QBT_WEBUI_PORT: "8080"
            WEBUI_PORT: "8080" 
            QBT_PROFILE: "/config"
          # Add simple startup delay
          command: ["/bin/sh"]
          args: ["-c", "sleep 30 && /entrypoint.sh"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
  service:
    qbittorrent:
      enabled: true
      controller: main
      primary: true
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 8080
          protocol: HTTP
          targetPort: 8080
  ingress:
    main:
      enabled: false
  persistence:
    qbittorrent-config:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/config/qbittorrent"
      advancedMounts:
        main:
          main:
            - path: /config
              readOnly: false
    downloads:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/downloads"
      advancedMounts:
        main:
          main:
            - path: /downloads
              readOnly: false
virtualService:
  enabled: true
  name: "qbittorrent-virtualservice"
  host: "qbittorrent.home.lan"
  gateway: "istio-system/istio-ingressgateway"
  prefix: "/"
  service:
    host: "qbittorrent.download.svc.cluster.local"  # Fixed: should be download namespace, not qbittorrent
    port: 8080
  timeout: "300s"
  retries:
    attempts: 2
    perTryTimeout: "2s"
