apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:qwnHNVYWAiQb6XNAh6qrj3bo0g9agEURVitooqGyTm5c/m7s5pcO/g==,iv:iikDYJg6knOpmUKEaSo+4HNwOMvI1tJs+gcsamfsK+Y=,tag:cbdajitalSnXI7IQchXqMA==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:uuyqEL389JuCUwfjUYEe+NNEusXzNteYVpTJ3ATLHWoR+MtWPCHbqA==,iv:LeFD3UTyRQg1Kl5KvsiwRxsffUdsZ3uzlgjmwbMjKNY=,tag:mSpn9eX5TpMtxRKyD8rYLg==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:la+LkPUX,iv:jxiaHFZwhqRhPuZtPHMPBP5zFvw4gzLyClNs4/Fugg0=,tag:y95jVMFlBNYtEDDZ5ResAQ==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:sa5LIDg=,iv:/x2RokUBLtbqSMqsskJDJQkqwn7LLt7PdnMMxsca/hE=,tag:LsE/ZXIdZ2azvXPqSBiyqg==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:bm8x4210Gk1uUp01/BPG/HNuV7LVi3W+gNEZ0vuI+9lWEahBw/M+u1bV3GGSJ731OfUmDfk=,iv:tJ0bF6eNwCAuEqyMMiV3w57PSj2lSGwrOifKfyK0kkE=,tag:aC+IKXwRIl3EfNZqYsJeGQ==,type:str]
    RENOVATE_USERNAME: ENC[AES256_GCM,data:6NHYL6nBkPqw4sFdJg==,iv:CuNPIc58P561wV4jCFmdgnDYxR7VdTEJ3PtS5lMCfck=,tag:vDNSPuQ9oyfhPr0bDANvHg==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:RuEME8g=,iv:fyavGP7ZaSqV0kRPbxDSuAot7VnlhV5a4Y+5INLEof0=,tag:ISeKSHz2SyBGAdJFbCjX1Q==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZlRJd2tpUlpaVGV2ajB0
            SlRjWnl3Q09FZVJzMVhmd1ZrZFpteks3a1FFCndFZE5tb3QvZFZNZVRlbkxxNU5J
            Y3U1b1RmY2VmSjRMZzZIVlNBSVlNYk0KLS0tIEE5YllVMFQ1b3FRZEVKWVdvbDdE
            RkJQeDEvbmcvcy9kdVRyQURmMWl4QmMKRiudWZTykMXMQdP9eCyAPgpowpKZiTXm
            wy1b0AM5cu9yvbcOFiqnM0Zln3zA87MUWXOzF5WFhATGQgNvHXMc/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T16:13:35Z"
    mac: ENC[AES256_GCM,data:wvJJ/nwA81+CclJeRqGyKPVAmalPi/EalHfj/0BhY6JVZBh+0gLsMuE5NGulqMrVJ1wvpKAfoxjJ80k44V4vL/TL3cHXaasrW8YSGkM2xUP0RD2wlIvrK/fHFwt0T+HOl1BS+f04/xIHhW2YcIC4tVouZOkbjD5k6zs9vvFW47Y=,iv:3qOlYOZkMHN/ZmprzEbzZEzybh8gi5+W6cHBSCDDWyw=,tag:Qq/wzk6O+RV/cu0/Ogp7Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
