apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx-ingress
      version: 1.2.x
    interval: 5h
    sourceRef:
      kind: HelmRepository
      name: nginx
  interval: 1h
  releaseName: nginx

