---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
  interval: 1h
  timeout: 10m
  values:
    cephClusterSpec:
      cleanupPolicy:
        wipeDevicesFromOtherClusters: true
      crashCollector:
        disable: false
      csi:
        readAffinity:
          enabled: true
          crushLocationLabels:
            - kubernetes.io/hostname
      dashboard:
        enabled: false
        # urlPrefix: /
        # ssl: false
        # prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090
      healthCheck:
        muteHealthWarning:
          AUTH_INSECURE_ROTATING_SERVICE_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_CLIENT_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_KEYS_ALLOWED:
            policy: mute
          AUTH_INSECURE_KEYS_CREATABLE:
            policy: mute
      mgr:
        count: 2
        modules:
          - name: pg_autoscaler
            enabled: true
      network:
        connections:
          requireMsgr2: true
      resources:
    mon:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi

    mgr:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

    osd:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        memory: 4Gi

    # These are the important ones for the Job you're currently stuck on.
    cmd-reporter:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        memory: 256Mi

    cleanup:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        memory: 256Mi

    crashcollector:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        memory: 64Mi

    exporter:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        memory: 128Mi

    logcollector:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        memory: 256Mi

    mgr-sidecar:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        memory: 100Mi

    prepareosd:
      requests:
        cpu: 100m
        memory: 50Mi
      security:
        cephx:
          daemon:
            keyRotationPolicy: KeyGeneration
            keyGeneration: 2
          csi:
            keyType: aes
      storage:
        devicePathFilter: /dev/disk/by-id/nvme-.*(Patriot_M\.2_P320_512GB|SAMSUNG_MZVLW512HMJP).*
        useAllDevices: false
        useAllNodes: true
    monitoring:
      enabled: true
      createPrometheusRules: true
    toolbox:
      enabled: true
    route:
      dashboard:
        host:
          name: rook.woo-ops.dev
          path: /
          pathType: PathPrefix
        parentRefs:
          - name: envoy-internal
            namespace: networking
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          allowVolumeExpansion: true
          isDefault: true
          mountOptions:
            - discard
          parameters:
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-publish-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            imageFeatures: deep-flatten,exclusive-lock,fast-diff,layering,object-map
            imageFormat: "2"
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-block
      isDefault: true
      deletionPolicy: Delete
    cephFileSystems: []
    cephObjectStores: []
