apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-share-pv
spec:
  capacity:
    storage: 1Mi
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.0.200"
    path: /mnt/pool/share/media
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - nconnect=16
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-share-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
  volumeName: media-nfs-share-pv
