{{- if .Values.virtualservice.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "jellyfin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.virtualservice.host }}
  gateways:
  - {{ .Values.virtualservice.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "jellyfin.fullname" . }}
        port:
          number: 8096
    timeout: 300s
    headers:
      request:
        set:
          X-Forwarded-Proto: "https"
          X-Forwarded-For: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
{{- end }}
