apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.13
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
              UPTIME_KUMA_PORT: "3001"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
    service:
      app:
        enabled: true
        primary: true
        type: ClusterIP
        controller: app
        ports:
          http:
            enabled: true
            primary: true
            port: 80
            protocol: HTTP
            targetPort: 3001
    ingress:
      app:
        enabled: false
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /app/data
            readOnly: false
