apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: 1
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
              UPTIME_KUMA_PORT: "3001"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3001
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3001
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 3
    service:
      main:
        enabled: true
        primary: true
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            primary: true
            port: 80
            protocol: HTTP
            targetPort: 3001
    ingress:
      main:
        enabled: false
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
        advancedMounts:
          main:
            main:
              - path: /app/data
                readOnly: false
