apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-ops-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/woobay/homelab.git
        revision: HEAD
        directories:
          - path: kubernetes/*
  template:
    metadata:
      name: '{{if eq .path.basename "argocd-self"}}argocd{{else}}{{.path.basename}}{{end}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/woobay/homelab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{if eq .path.basename "argocd-self"}}argocd{{else}}{{.path.basename}}{{end}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
