apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent-route
spec:
  parentRefs:
    - name: main-gateway
      namespace: kube-system
  hostnames:
    - "qbittorrent.homelab"
  rules:
    - backendRefs:
        - name: qbittorrent
          port: 80
