apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 30m
  path: ../../infrastructure
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
