version: '3'

includes:
  sops: .taskfiles/sops/Taskfile.yaml
  talos: .taskfiles/talos/Taskfile.yaml
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml

vars:
  TALOSCONFIG: "talos/clusterconfig/talosconfig"

env:
  TALOSCONFIG: "{{.TALOSCONFIG}}"

tasks:
  default:
    desc: Show available task categories
    silent: true
    cmds:
      - echo "Available task categories:"
      - echo "  task sops:<tab>     - SOPS encryption tasks"
      - echo "  task talos:<tab>    - Talos cluster management"
      - echo "  task k8s:<tab>      - Kubernetes bootstrap tasks"

  help:
    desc: Show this help
    cmds:
      - task: default
