apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:1ZqUfJDJ9xnwy1XH0kAkyvUGJMJKwI9v1cAEXm6L4ic=,iv:ikiZ+2KQoVY5fjWXJcWgGH0LOY3ZdsfXVQEhp5ubfIs=,tag:hg32D08oZcUrYKro5plbaA==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUGhKcHpsOERLL1FQQXoy
            YytrUXUxTnNwcThDYlBIUmdWRmU4WG4xaGxzCk1YVTZZcWV3d0FyRzBKblE0cWV3
            QlBucndhZlY5WkFXWXFCQzBRYjh0RmcKLS0tIGlqQm04QnF2eHlUQVI4Q3hJZ1JN
            WkpSb3NYV016dTRXT0tvRXdpZmpQTTgKRxck2dlEDaukjazchITCYLm71fULf2vI
            nWSpZB9LvBL4miAsOR1VE5hpeZU9TcPiyv7phC9InF4Q0sbnVFn3UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T21:54:06Z"
    mac: ENC[AES256_GCM,data:7AYx/5ii/hyoPF4oqcN9zrnumG+zhUCD0Y8hdJccy/+oULOfuoKhno25F/9HVTn4yoUeNxuPC2meYXpRBQitcsSYy7TcgUaKAEQhhvYHyA0uV/9A+9lZzKF8/s4opkMxLRZvcWJwocwcGJAz1xdSj18wFgoCQCyYpgFGxUdeZZ0=,iv:ZZ03DOSJOxgcISk+GQmNmYCaeWZ6KZAFkunaIY1jxno=,tag:H2AeEEq3qp039TRVcSoKhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
