---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ac-database
spec:
  interval: 1h
  path: ./kubernetes/apps/games/wow/db
  postBuild:
    substitute:
      APP: ac-database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: games
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ac-authserver
spec:
  interval: 1h
  path: ./kubernetes/apps/games/wow/auth-server
  postBuild:
    substitute:
      APP: ac-authserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: games
  dependsOn:
    - name: ac-database
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ac-worldserver
spec:
  interval: 1h
  path: ./kubernetes/apps/games/wow/world-server
  postBuild:
    substitute:
      APP: ac-database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: games
  dependsOn:
    - name: ac-database
