---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: connector
  namespace: networking
spec:
  hostnamePrefix: "wow-connector"
  tags:
    - "tag:k8s-operator"
  subnetRouter:
    advertiseRoutes:
      - 192.168.20.0/24
  replicas: 1
