apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: metallb
      version: 6.3.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1h
  releaseName: metallb
  targetNamespace: infrastructure
  #I need to add the values from mt idressPool.yaml here which is a kind IpAddressPool 
  valuesFrom:
  - kind: AddressPool
    name: first-pool
    namespace: infrastructure
    valuesKey: adressPool.yaml
