apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: metallb
      version: 6.3.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1h
  releaseName: metallb
  targetNamespace: infrastructure
