ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: ""
      externalTrafficPolicy: Local
    
    # Disable Istio sidecar injection
    podAnnotations:
      sidecar.istio.io/inject: "false"
    
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    
    config:
      proxy-body-size: "100m"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  
  defaultBackend:
    enabled: true
    podAnnotations:
      sidecar.istio.io/inject: "false"
