apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - priorityclass.yaml
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.10.1
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true
    valuesFile: values.yaml
