apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: longhorn
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        namespace: longhorn-system
        name: longhorn
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: true
    csi:
      attacherReplicaCount: 3
      provisionerReplicaCount: 3
      resizerReplicaCount: 3
      snapshotterReplicaCount: 3
    ingress:
      enabled: false
