app-template:
  controllers:
    main:
      enabled: true
      type: deployment
      replicas: 1
      containers:
        main:
          image:
            repository: linuxserver/prowlarr
            tag: latest
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            PUID: 1000
            PGID: 1000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      # Pod-level security context
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
  service:
    main:
      enabled: true
      primary: true
      type: ClusterIP
      controller: main
      ports:
        http:
          enabled: true
          primary: true
          port: 9696
          protocol: HTTP
          targetPort: 9696
  ingress:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/config/prowlarr"
      globalMounts:
        - path: /config
          readOnly: false
virtualService:
  enabled: true
  name: "prowlarr-virtualservice"
  host: "prowlarr.home.lan"
  gateway: "istio-system/istio-ingressgateway"
  prefix: "/"
  service:
    host: "prowlarr.prowlarr.svc.cluster.local"
    port: 9696
  timeout: "300s"
  retries:
    attempts: 2
    perTryTimeout: "2s"
