app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    hostNetwork: false
    annotations:
      sidecar.istio.io/inject: "false"
    securityContext:
      sysctls:
        - name: net.ipv4.conf.all.src_valid_mark
          value: "1"
        - name: net.ipv6.conf.all.disable_ipv6
          value: "0"
  controllers:
    main:
      pod:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
      containers:
        main:
          image:
            repository: qbittorrentofficial/qbittorrent-nox
            tag: latest
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            QBT_LEGAL_NOTICE: "confirm"
            QBT_TORRENTING_PORT: "6881"
            QBT_WEBUI_PORT: "8080"
            WEBUI_PORT: "8080" 
            QBT_PROFILE: "/config"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
        gluetun:
          dependsOn: main
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: latest
            pullPolicy: IfNotPresent
          env:
            DOT: "off"
            DNS_KEEP_NAMESERVER: "on"
            DNS_ADDRESS: "103.86.96.100"
            TZ: "America/New_York"
            VPN_SERVICE_PROVIDER: nordvpn
            VPN_TYPE: openvpn
            OPENVPN_USER:
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: username
            OPENVPN_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: password
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
        sonarr:
          image:
            repository: linuxserver/sonarr
            tag: latest
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            PUID: 1000
            PGID: 1000
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
        radarr:
          image:
            repository: linuxserver/radarr
            tag: latest
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            PUID: 1000
            PGID: 1000
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
        prowlarr:
          image:
            repository: linuxserver/prowlarr
            tag: latest
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            PUID: 1000
            PGID: 1000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
  service:
    qbittorrent:
      enabled: true
      controller: main
      primary: true
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 8080
          protocol: HTTP
          targetPort: 8080
        torrenting:
          enabled: true
          port: 6881
          protocol: TCP
          targetPort: 6881
    sonarr:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 8989
          protocol: HTTP
          targetPort: 8989
    radarr:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 7878
          protocol: HTTP
          targetPort: 7878
    prowlarr:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 9696
          protocol: HTTP
          targetPort: 9696
  ingress:
    main:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - host: media.lan
          paths:
            - path: /qbittorrent
              pathType: Prefix
              service:
                identifier: qbittorrent
                port: 8080
            - path: /sonarr
              pathType: Prefix
              service:
                identifier: sonarr
                port: 8989
            - path: /radarr
              pathType: Prefix
              service:
                identifier: radarr
                port: 7878
            - path: /prowlarr
              pathType: Prefix
              service:
                identifier: prowlarr
                port: 9696
  persistence:
    qbittorrent-config:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/config/qbittorrent"
      advancedMounts:
        main:
          main:
            - path: /config
              readOnly: false
    sonarr-config:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/config/sonarr"
      advancedMounts:
        main:
          sonarr:
            - path: /config
              readOnly: false
    radarr-config:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/config/radarr"
      advancedMounts:
        main:
          radarr:
            - path: /config
              readOnly: false
    prowlarr-config:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/config/prowlarr"
      advancedMounts:
        main:
          prowlarr:
            - path: /config
              readOnly: false
    media:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/media"
      advancedMounts:
        main:
          sonarr:
            - path: /media
              readOnly: false
          radarr:
            - path: /media
              readOnly: false
    downloads:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/downloads"
      advancedMounts:
        main:
          main:
            - path: /downloads
              readOnly: false
          sonarr:
            - path: /downloads
              readOnly: false
          radarr:
            - path: /downloads
              readOnly: false
