apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    localpv-provisioner:
      enabled: true
      rbac:
        create: true
      localpv:
        basePath: /var/openebs/local
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: Exists
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: true
        basePath: /var/openebs/local
        reclaimPolicy: Delete
    mayastor:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    lvm-localpv:
      enabled: false
    zfs-localpv:
      enabled: false
    openebs-ndm:
      enabled: false
