apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          app:
            image:
              repository: linuxserver/sonarr
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi
            probes:
              liveness:
                enabled: true
                type: HTTP
                spec:
                  httpGet:
                    path: /ping
                    port: 8989
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                type: HTTP
                spec:
                  httpGet:
                    path: /ping
                    port: 8989
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: true
                type: HTTP
                spec:
                  httpGet:
                    path: /ping
                    port: 8989
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
        # Pod-level security context
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
    service:
      app:
        enabled: true
        primary: true
        type: ClusterIP
        controller: app
        ports:
          http:
            enabled: true
            primary: true
            port: 80
            protocol: HTTP
            targetPort: 8989
    ingress:
      app:
        enabled: false
    persistence:
      config:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/config/sonarr"
        globalMounts:
          - path: /config
            readOnly: false
      media:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/media"
        globalMounts:
          - path: /media
            readOnly: false
      downloads:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/downloads"
        globalMounts:
          - path: /downloads
            readOnly: false
