apiVersion: v2
name: sonarr
description: A Helm chart for Sonarr TV series management
type: application
version: 0.1.0

dependencies:
  - name: app-template
    version: 4.2.0
    repository: https://bjw-s-labs.github.io/helm-charts/
