apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      app:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          app:
            image:
              repository: linuxserver/radarr
              tag: 5.27.5.10198-ls282
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
    service:
      app:
        enabled: true
        primary: true
        type: ClusterIP
        controller: app
        ports:
          http:
            enabled: true
            primary: true
            port: 80
            protocol: HTTP
            targetPort: 7878
    route:
      app:
        annotations:
            url: https://{{ .Release.Name }}.woo-ops.dev/
        hostnames:
          - "{{ .Release.Name }}.woo-ops.dev"
          - radarr.woo-ops.dev
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
    ingress:
      app:
        enabled: false
    persistence:
      config:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/config/radarr"
        globalMounts:
          - path: /config
            readOnly: false
      media:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/main/media"
        globalMounts:
          - path: /media
            readOnly: false
      downloads:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/main/downloads"
        globalMounts:
          - path: /downloads
            readOnly: false
