---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
spec:
  interval: 1h
  url: https://bjw-s-labs.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseer
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          main:
            image:
              repository: fallenbagel/jellyseerr
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
              PORT: "5055"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
    service:
      main:
        enabled: true
        primary: true
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            primary: true
            port: 80
            protocol: HTTP
            targetPort: 5055
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/config/jellyseer"
        globalMounts:
          - path: /app/config
            readOnly: false
      media:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/media"
        globalMounts:
          - path: /media
            readOnly: false
      downloads:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/downloads"
        globalMounts:
          - path: /downloads
            readOnly: false
---
