apiVersion: v1
kind: Secret
metadata:
    name: ac-database-secret
    namespace: games
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:qMq6/gQpfq/UpsCWIzWLHj/1FT37,iv:ahorHxcVE0giZb1EGD7w4K8F3ABaijts5xqq8XjPtao=,tag:ZRvuC07dli94NAFC6mJtAA==,type:str]
    AC_LOGIN_DATABASE_INFO: ENC[AES256_GCM,data:62BKnaZ/DtVsbvlPudztx+a0BSJ+7HCzK7kBH3GK1/V8MHSfFSe2ajARKeihvRuNkDhy12X+,iv:KaLfaqiSTfwUx4OcmqIzIG5+6bI8q9S0yBw8yBPWmKc=,tag:GzQIZhW1C3nm3VasF+cZRQ==,type:str]
    AC_WORLD_DATABASE_INFO: ENC[AES256_GCM,data:aZpP+NtPmZe2DJDR6LiNBoun3JPdlfc8o7ElGXgajLrq8r8ebNmG2N9WZ3IRhtETno2vjLbDcQ==,iv:xsob2pCiIQfnINJ2s3ELy2JrsFIaeIQIG5XusBOV4tE=,tag:2UtrT7XHRCHKBI9GHfEIlA==,type:str]
    AC_CHARACTER_DATABASE_INFO: ENC[AES256_GCM,data:YOC8oKt+qXrXpHqkAQFMZG7uPDetbKTngQ+JTebZhQXHdKli3rp4nByLDTVc5AzGNhuSY7r59NZ60YBh,iv:mIq/zQdC5+QrWSCHcW4dowlasKnxfeWhPYgtIwtP5fw=,tag:mvMnITxGtfHtpyJF2leoqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dDVlOVd6OUlpZGFGSWkr
            cGZ3RlpGajRJM0dZQWl2WWZxRjYzU1RFZ0RNCkQyM0FhMDhYVlBQR3B1RldkWnZV
            L3B2VmFiMHhWNTM3MlZYM1R2cXVQWjAKLS0tIGJLRmZnQTFRRjVhV1RSZ0dMYVlW
            d2tSVjAwRnFHbmJxNVBEeXFyTWVTOWMKm6oQk93gV65IKQu00n0o/iBUsTeR+l15
            qWXQR0u5cU4iXFrevcfAb6bqMVE3++LwH4gUxUaLUMGVcqOiib3A1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T21:50:16Z"
    mac: ENC[AES256_GCM,data:4EchnbfxXkyWT13welh5sgCCWTufOaSwAp99eKL2WfvUx5u8/88HY1JKnyKqz4nSqCl5ijjipl6TODt3Ug2pJ9oCkkeOknl3dcF2PoP4UcOa1Q9GZmRtbHe/Pmv2KjY6GsEmDozRT5IhPjomWnUGI64FHxlGdLGxaTz4BRyzi58=,iv:aYTTZYXVAPmQUsQtrIKpl8jTi90mSIztfCfnxkqx27k=,tag:oiJME7J9rdoLA6gwk8IOsA==,type:str]
    version: 3.13.3
