apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
  namespace: coroot
spec:
  clickhouse:
    shards: 2
    replicas: 2
  storage:
    className: nfs-client
    size: 10Gi
  prometheus:
    storage:
      className: nfs-client
      size: 10Gi
  clickhouse:
    storage:
      className: nfs-client
      size: 20Gi
 

