apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coroot
spec:
  interval: 1h
  url: https://coroot.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app coroot-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: coroot-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: coroot
        namespace: observability
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values: {}
