apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel-hub
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          app:
            image:
              repository: henrygd/beszel
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
              PORT: "8090"
              HUB_PORT: "45877"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
    service:
      app:
        enabled: true
        primary: true
        type: ClusterIP
        controller: app
        ports:
          web:
            enabled: true
            primary: true
            port: 8090
            protocol: HTTP
            targetPort: 8090
          agent:
            enabled: true
            port: 45877
            protocol: TCP
            targetPort: 45877
    ingress:
      app:
        enabled: false
    persistence:
      data:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/config/beszel"
        globalMounts:
          - path: /app/data
            readOnly: false
