apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      hub:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          hub:
            image:
              repository: henrygd/beszel
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
              PORT: "8090"
              HUB_PORT: "45877"
              TOKEN: "bb99442f-cc62-49d8-835d-6543c0805020"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            securityContext:
              runAsUser: 0
              runAsGroup: 0
      agent:
        enabled: true
        type: daemonset
        containers:
          agent:
            image:
              repository: henrygd/beszel-agent
              tag: latest
              pullPolicy: Always
            env:
              PORT: "45876"
              KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKh+aRPchFrHEE6qnlxNM0D/w/Sp2tX/EuVW4cvLrWYk"
        pod:
          hostNetwork: true
          restartPolicy: Always
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
              operator: Exists
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Exists
    service:
      hub:
        enabled: true
        primary: true
        type: ClusterIP
        controller: hub
        ports:
          web:
            enabled: true
            primary: true
            port: 8090
            protocol: HTTP
            targetPort: 8090
          agent-hub:
            enabled: true
            port: 45877
            protocol: TCP
            targetPort: 45877
      agent:
        enabled: false
    ingress:
      hub:
        enabled: false
    persistence:
      data:
        enabled: true
        type: nfs
        server: "192.168.0.5"
        path: "/mnt/storage/config/beszel"
        advancedMounts:
          hub:
            hub:
              - path: /app/data
                readOnly: false
