apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts/cert-manager
    version: v1.18.2
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - cluster-issuer.yaml
