# Global settings
global:
  leaderElection:
    namespace: "cert-manager"

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

webhook:
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 64Mi

cainjector:
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

logLevel: 2

