apiVersion: v2
name: qbittorrent
description: A Helm chart for qBittorrent with Gluetun VPN
type: application
version: 0.1.0

dependencies:
  - name: app-template
    version: 4.2.0
    repository: https://bjw-s-labs.github.io/helm-charts/
