---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  # enable this for dev / staging environments to use internal IP load balancer only
  #- internal-loadbalancer-service.patch.yaml
