---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-system
components:
  - ../../components/namespace
  - ../../components/sops
resources:
  - ./actions-runner-controller/ks.yaml
