apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: app-template
  repo: https://bjw-s-labs.github.io/helm-charts/
  version: 4.2.0
  releaseName: qbittorrent
  namespace: qbittorrent
  valuesFile: values.yaml

resources:
  - namespace.yaml
  - httproute.yaml
