controllers:
  main:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/qbittorrent
          tag: "5.1.2"
          pullPolicy: IfNotPresent
        env:
          TZ: "America/New_York"
          QBT_PROFILE: "/config"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      gluetun:
        dependsOn: main
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: latest
          pullPolicy: IfNotPresent
        env:
          TZ: "America/New_York"
          FIREWALL_INPUT_PORTS: "8080"
          VPN_SERVICE_PROVIDER: nordvpn
          VPN_TYPE: openvpn
          OPENVPN_USER:
            valueFrom:
              secretKeyRef:
                name: nordvpn-credentials
                key: username
          OPENVPN_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: nordvpn-credentials
                key: password
        securityContext:
          runAsGroup: 0
          runAsUser: 0
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        port: 80
        protocol: HTTP
        targetPort: 8080
ingress:
  main:
    enabled: false
persistence:
  config:
    enabled: true
    type: nfs
    server: "192.168.0.5"
    path: "/mnt/storage/config/qbittorrent"
    advancedMounts:
      main:
        main:
          - path: /config
            readOnly: false
  downloads:
    enabled: true
    type: nfs
    server: "192.168.0.5"
    path: "/mnt/storage/downloads"
    advancedMounts:
      main:
        main:
          - path: /downloads
            readOnly: false
