apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-daemonset
spec:
  mode: daemonset
  serviceAccount: otel-daemonset-collector
  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      readOnly: true
  volumes:
    - name: hostfs
      hostPath:
        path: /
  env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: NEW_RELIC_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: newrelic-license
          key: license-key
    - name: CLUSTER_NAME
      value: homelab
  config:
    receivers:
      hostmetrics:
        root_path: /hostfs
        collection_interval: 1m
        scrapers:
          cpu:
            metrics:
              system.cpu.time:
                enabled: false
              system.cpu.utilization:
                enabled: true
              system.cpu.logical.count:
                enabled: true
          load:
          memory:
            metrics:
              system.memory.utilization:
                enabled: true
          paging:
            metrics:
              system.paging.utilization:
                enabled: false
              system.paging.faults:
                enabled: false
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
            exclude_mount_points:
              mount_points:
                - ^/var/lib/containers/storage/overlay$
              match_type: regexp
          disk:
            metrics:
              system.disk.merged:
                enabled: false
              system.disk.pending_operations:
                enabled: false
              system.disk.weighted_io_time:
                enabled: false
          network:
            metrics:
              system.network.connections:
                enabled: false

      kubeletstats:
        collection_interval: 1m
        endpoint: "${env:KUBE_NODE_NAME}:10250"
        auth_type: "serviceAccount"
        insecure_skip_verify: true
        metrics:
          k8s.container.cpu_limit_utilization:
            enabled: true
          k8s.pod.cpu_limit_utilization:
            enabled: true
          k8s.pod.cpu_request_utilization:
            enabled: true
          k8s.pod.memory_limit_utilization:
            enabled: true
          k8s.pod.memory_request_utilization:
            enabled: true

      prometheus:
        config:
          scrape_configs:
            - job_name: cadvisor
              scrape_interval: 1m
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - replacement: kubernetes.default.svc.cluster.local:443
                  target_label: __address__
                - regex: (.+)
                  replacement: /api/v1/nodes/$${1}/proxy/metrics/cadvisor
                  source_labels:
                    - __meta_kubernetes_node_name
                  target_label: __metrics_path__
                - action: replace
                  target_label: job_label
                  replacement: cadvisor
                - source_labels: [__meta_kubernetes_node_name]
                  regex: ${env:KUBE_NODE_NAME}
                  action: keep
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
                server_name: kubernetes

            - job_name: kubelet
              scrape_interval: 1m
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - replacement: kubernetes.default.svc.cluster.local:443
                  target_label: __address__
                - regex: (.+)
                  replacement: /api/v1/nodes/$${1}/proxy/metrics
                  source_labels:
                    - __meta_kubernetes_node_name
                  target_label: __metrics_path__
                - action: replace
                  target_label: job_label
                  replacement: kubelet
                - source_labels: [__meta_kubernetes_node_name]
                  regex: ${env:KUBE_NODE_NAME}
                  action: keep
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
                server_name: kubernetes

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25

      resourcedetection/env:
        detectors: ["env", "system"]
        override: false
        system:
          hostname_sources: ["os"]
          resource_attributes:
            host.name:
              enabled: false

      resource/newrelic:
        attributes:
          - key: k8s.cluster.name
            action: upsert
            value: ${env:CLUSTER_NAME}
          - key: newrelic.entity.type
            action: upsert
            value: "k8s"

      metricstransform/k8s_cluster_info:
        transforms:
          - include: kubernetes_build_info
            action: update
            new_name: k8s.cluster.info

      metricstransform/hostmetrics_cpu:
        transforms:
          - include: system.cpu.utilization
            action: update
            operations:
              - action: aggregate_labels
                label_set: [state]
                aggregation_type: mean
          - include: system.paging.operations
            action: update
            operations:
              - action: aggregate_labels
                label_set: [direction]
                aggregation_type: sum

      transform/low_data_mode_inator:
        metric_statements:
          - context: metric
            statements:
              - set(metric.description, "")
              - set(metric.unit, "")
          - context: datapoint
            statements:
              - delete_key(datapoint.attributes, "id")
              - delete_key(datapoint.attributes, "name")
              - delete_key(datapoint.attributes, "interface")
              - delete_key(datapoint.attributes, "cpu")

      resource/low_data_mode_inator:
        attributes:
          - key: http.scheme
            action: delete
          - key: net.host.name
            action: delete
          - key: net.host.port
            action: delete
          - key: url.scheme
            action: delete
          - key: server.address
            action: delete

      filter/lowdatamode:
        metrics:
          include:
            match_type: strict
            metric_names:
              # cAdvisor (prometheus receiver)
              - container_cpu_cfs_periods_total
              - container_cpu_cfs_throttled_periods_total
              - container_cpu_usage_seconds_total
              - container_memory_mapped_file
              - container_memory_working_set_bytes
              - container_network_receive_bytes_total
              - container_network_receive_errors_total
              - container_network_transmit_bytes_total
              - container_network_transmit_errors_total
              - container_spec_memory_limit_bytes
              # Kubelet (prometheus receiver)
              - go_goroutines
              - go_threads
              - process_resident_memory_bytes
              - kubernetes_build_info
              - k8s.cluster.info
              # KubeletStats (kubeletstats receiver)
              - container.cpu.usage
              - container.filesystem.available
              - container.filesystem.capacity
              - container.filesystem.usage
              - container.memory.usage
              - k8s.node.cpu.time
              - k8s.node.cpu.usage
              - k8s.node.filesystem.capacity
              - k8s.node.filesystem.usage
              - k8s.node.memory.available
              - k8s.node.memory.working_set
              - k8s.pod.cpu_limit_utilization
              - k8s.pod.cpu_request_utilization
              - k8s.pod.filesystem.available
              - k8s.pod.filesystem.capacity
              - k8s.pod.filesystem.usage
              - k8s.pod.memory_limit_utilization
              - k8s.pod.memory_request_utilization
              - k8s.pod.memory.working_set
              - k8s.pod.network.io
              # HostMetrics (hostmetrics receiver)
              - system.cpu.load_average.15m
              - system.cpu.load_average.1m
              - system.cpu.load_average.5m
              - system.cpu.utilization
              - system.cpu.logical.count
              - system.disk.io
              - system.disk.io_time
              - system.disk.operation_time
              - system.disk.operations
              - system.filesystem.inodes.usage
              - system.filesystem.usage
              - system.filesystem.utilization
              - system.memory.usage
              - system.memory.utilization
              - system.network.errors
              - system.network.io
              - system.network.packets
              - system.paging.usage
              - system.paging.operations

      filter/exclude_filesystem_utilization:
        metrics:
          datapoint:
            - 'metric.name == "system.filesystem.utilization" and attributes["type"] == "squashfs"'

      filter/exclude_filesystem_usage:
        metrics:
          datapoint:
            - 'metric.name == "system.filesystem.usage" and attributes["type"] == "squashfs"'
            - 'metric.name == "system.filesystem.usage" and attributes["state"] == "reserved"'

      filter/exclude_filesystem_inodes_usage:
        metrics:
          datapoint:
            - 'metric.name == "system.filesystem.inodes.usage" and attributes["type"] == "squashfs"'
            - 'metric.name == "system.filesystem.inodes.usage" and attributes["state"] == "reserved"'

      filter/exclude_system_disk:
        metrics:
          datapoint:
            - 'metric.name == "system.disk.operations" and IsMatch(attributes["device"], "^loop.*") == true'
            - 'metric.name == "system.disk.io" and IsMatch(attributes["device"], "^loop.*") == true'
            - 'metric.name == "system.disk.io_time" and IsMatch(attributes["device"], "^loop.*") == true'
            - 'metric.name == "system.disk.operation_time" and IsMatch(attributes["device"], "^loop.*") == true'

      filter/exclude_system_paging:
        metrics:
          datapoint:
            - 'metric.name == "system.paging.usage" and attributes["state"] == "cached"'
            - 'metric.name == "system.paging.operations" and attributes["type"] == "cached"'

      filter/exclude_network:
        metrics:
          datapoint:
            - 'IsMatch(metric.name, "^system.network.*") == true and attributes["device"] == "lo"'

      filter/exclude_container_zero_values:
        metrics:
          datapoint:
            - 'metric.name == "container_network_receive_errors_total" and value_double < 0.5'
            - 'metric.name == "container_network_transmit_errors_total" and value_double < 0.5'
            - 'metric.name == "container_network_transmit_bytes_total" and value_double < 0.5'
            - 'metric.name == "container_network_receive_bytes_total" and value_double < 0.5'

      attributes/exclude_system_paging:
        include:
          match_type: strict
          metric_names:
            - system.paging.operations
        actions:
          - key: type
            action: delete
      groupbyattrs:
        keys:
          - pod
          - uid
          - container
          - daemonset
          - replicaset
          - statefulset
          - deployment
          - cronjob
          - job_name
          - node
          - namespace

      transform/ksm:
        metric_statements:
          - delete_key(resource.attributes, "k8s.node.name")
          - delete_key(resource.attributes, "k8s.namespace.name")
          - delete_key(resource.attributes, "k8s.pod.uid")
          - delete_key(resource.attributes, "k8s.pod.name")
          - delete_key(resource.attributes, "k8s.container.name")
          - delete_key(resource.attributes, "k8s.replicaset.name")
          - delete_key(resource.attributes, "k8s.deployment.name")
          - delete_key(resource.attributes, "k8s.statefulset.name")
          - delete_key(resource.attributes, "k8s.daemonset.name")
          - delete_key(resource.attributes, "k8s.job.name")
          - set(resource.attributes["k8s.pod.uid"], resource.attributes["uid"])
          - set(resource.attributes["k8s.node.name"], resource.attributes["node"])
          - set(resource.attributes["k8s.namespace.name"], resource.attributes["namespace"])
          - set(resource.attributes["k8s.pod.name"], resource.attributes["pod"])
          - set(resource.attributes["k8s.container.name"], resource.attributes["container"])
          - set(resource.attributes["k8s.replicaset.name"], resource.attributes["replicaset"])
          - set(resource.attributes["k8s.deployment.name"], resource.attributes["deployment"])
          - set(resource.attributes["k8s.statefulset.name"], resource.attributes["statefulset"])
          - set(resource.attributes["k8s.daemonset.name"], resource.attributes["daemonset"])
          - set(resource.attributes["k8s.job.name"], resource.attributes["job_name"])
          - set(resource.attributes["k8s.cronjob.name"], resource.attributes["cronjob"])
          - delete_key(resource.attributes, "uid")
          - delete_key(resource.attributes, "node")
          - delete_key(resource.attributes, "namespace")
          - delete_key(resource.attributes, "pod")
          - delete_key(resource.attributes, "container")
          - delete_key(resource.attributes, "replicaset")
          - delete_key(resource.attributes, "deployment")
          - delete_key(resource.attributes, "statefulset")
          - delete_key(resource.attributes, "daemonset")
          - delete_key(resource.attributes, "job_name")
          - delete_key(resource.attributes, "cronjob")

      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.daemonset.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.replicaset.name
            - k8s.statefulset.name
            - k8s.cronjob.name
            - k8s.job.name
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: resource_attribute
              name: k8s.pod.name
      cumulativetodelta:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size: 800

    exporters:
      debug:
        verbosity: detailed
      # otlp/gateway:
      #   endpoint: otel-gateway-collector:4317
      #   tls:
      #     insecure: true
      #   sending_queue:
      #     enabled: true
      #     num_consumers: 4
      #     queue_size: 1000
      #   retry_on_failure:
      #     enabled: true
      #     initial_interval: 5s
      #     max_interval: 30s
      #     max_elapsed_time: 300s

    service:
      pipelines:
        metrics/host:
          receivers:
            - hostmetrics
            - kubeletstats
          processors:
            - memory_limiter
            - filter/lowdatamode
            - metricstransform/hostmetrics_cpu
            - filter/exclude_filesystem_utilization
            - filter/exclude_filesystem_usage
            - filter/exclude_filesystem_inodes_usage
            - filter/exclude_system_disk
            - filter/exclude_system_paging
            - filter/exclude_network
            - attributes/exclude_system_paging
            - resourcedetection/env
            - k8sattributes
            - resource/newrelic
            - transform/low_data_mode_inator
            - resource/low_data_mode_inator
            - cumulativetodelta
            - batch
          exporters:
            - otlp/gateway

        metrics/prometheus:
          receivers:
            - prometheus
          processors:
            - memory_limiter
            - metricstransform/k8s_cluster_info
            - filter/lowdatamode
            - filter/exclude_container_zero_values
            - resourcedetection/env
            - resource/low_data_mode_inator
            - groupbyattrs
            - transform/ksm
            - k8sattributes
            - resource/newrelic
            - transform/low_data_mode_inator
            - cumulativetodelta
            - batch
          exporters:
            - otlp/gateway
