controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      main:
        image:
          repository: linuxserver/radarr
          tag: latest
          pullPolicy: IfNotPresent
        env:
          TZ: "America/New_York"
          PUID: 1000
          PGID: 1000
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        port: 80
        protocol: HTTP
        targetPort: 7878
ingress:
  main:
    enabled: false
persistence:
  config:
    enabled: true
    type: nfs
    server: "192.168.0.5"
    path: "/mnt/storage/config/radarr"
    globalMounts:
      - path: /config
        readOnly: false
  media:
    enabled: true
    type: nfs
    server: "192.168.0.5"
    path: "/mnt/storage/media"
    globalMounts:
      - path: /media
        readOnly: false
  downloads:
    enabled: true
    type: nfs
    server: "192.168.0.5"
    path: "/mnt/storage/downloads"
    globalMounts:
      - path: /downloads
        readOnly: false
