apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: networking
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:+Yh8zrJMp2qfIhyT8qVB4oI=,iv:l3doupBgXTfuXIEpWxq7mC02IPJNy+TykAA20UEfWNA=,tag:Bx1qvS2uLqDBrNuGxXYdxQ==,type:str]
    client_secret: ENC[AES256_GCM,data:Jdtp9Z2o+YUjL82BpW+yTNjhI8UI82SmdxocKTPGuWGUADd9r0uxSi70RvHzRFLJ2DqChxltfB8T9HiDSFkqdw==,iv:rwVSOyIrxxHSPurtWFlbMbd5c+m1cNdVHqk3xnpdeX4=,tag:dA6omni5OJ7ExpTCad0VSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML2lqTlBTV0ZyNUVuclph
            VG5NZW9jbHl1eHlZSWwrUjRvK1k1a3U3NHowCkcvYnVnd0hhSmx2VFREcldXemJJ
            eFNLYVZKb0NjOE5PUS9FN3NVRUF4UlEKLS0tIHhpL0pMcGJNRE95eHhYeEV6bjcz
            NzRYWkhWWk5hUTd5aEdQZnMxcmkrUkkKTTuBXaxRx8vMy7CeEjbe3bHfCHpVxlWr
            c/Ca1cSapEy8uYF5ikyY89+FHO0MK3ZQLoMcPjvZ/KaWQhnyEByM+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T21:50:07Z"
    mac: ENC[AES256_GCM,data:v7FftyogP85GViCgpXA6Jn0GYy7BwdY4PNEBeVndO0NXrVTFmZ24kssZc7POlvtA5Faj3CosrLLmZjXWfNx+uSFbXW7yndSgTtCxilpdH5axqkVvorDR7HvKX3OxXnQT+NN7rhLjs5vgfxnGA3XNfi2HCkd9eLHGgy9myBEtlXE=,iv:+pPFSsMHXw6B2ku1ih5tqtc2smlmarkr+NFAE1mxwH4=,tag:cHN9sRLwyIILYGZV8GDRog==,type:str]
    version: 3.13.3
