apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: networking
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:B1dozg6CnpmwTtQbbEN1NQ0=,iv:NVtNVbuQQgqnlYrZ/2ahuqoAYp9j63y7bSgD0xruJb8=,tag:ObEmwfpEhiV8V7C3VG6A2A==,type:str]
    client_secret: ENC[AES256_GCM,data:Y7HY7DpPyYOdwVYnYrBqLwkALAIZYzwAL8JfSiQU4LTj+aAVyNcy+x0WJekPZRj/dYbDUcge/K+Td+VF9kMC,iv:BvnsLN28OnPiaZzjn2I3PfjfYT1ifhtyq6Y5mJty21k=,tag:TLCuzx1ZLCUFyLDUskJWag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRVRaNFhJTTF0TWZSOEVP
            T29rWVVOVFJxWDJPMFFTZnpHNlIxZG5kaHpVCkdibFpoeitJQllRQ0gvU05QMEVj
            ZE55VlBZeVUrSHJEUW91N0NmVzM4aW8KLS0tIDhod3dtZDhWTC8wVEVBemFsa2t3
            WlFMZ1YxMEdZY1o5ZEdaODhhWlIvWGcKXEbi8cCQumJ/T+q4P9UN2zbSLapj8OVd
            tNHrLMORhmq/yz4MGN+xS/xOwF3/mQ3ODZNPnvrgUtKTIntSv10jVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T22:12:33Z"
    mac: ENC[AES256_GCM,data:1YfX95xabE1SmxuOHT0EA2fnhoqkkjSchdx9OHwcTHpGY7cgQNwDk1iC8Kvm08Flh1eylgjszGf1X8LLXs1NwqNKB+8yuWIlHtUsjIsGM3FzQ7KDulRdtCYLH8U6/yGRSKGOBQiOMIb/0pJiYAaMd3yc9FeRwwSQxpRLqn7CFqY=,iv:crJv/nZR0apR6thG81eRl9VY3woV1xk1qztmlgimdC0=,tag:WwUwdA6S3vIeVqTHyBSQ/g==,type:str]
    version: 3.13.3
