---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  interval: 1h
  values:
    csi:
      serviceMonitor:
        enabled: true
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits: {}
