# Values for bjw-s app-template dependency
app-template:
  controllers:
    main:
      enabled: true
      type: deployment
      replicas: 1
      
      containers:
        main:
          image:
            repository: jellyfin/jellyfin
            tag: latest
            pullPolicy: IfNotPresent
          
          env:
            TZ: "America/New_York"
            JELLYFIN_PublishedServerUrl: "jellyfin.home.lan"
          
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 8Gi
          
          probes:
            liveness:
              enabled: true
              type: HTTP
              spec:
                httpGet:
                  path: /health
                  port: 8096
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
            
            readiness:
              enabled: true
              type: HTTP
              spec:
                httpGet:
                  path: /health
                  port: 8096
                initialDelaySeconds: 10
                periodSeconds: 5
                timeoutSeconds: 3
                failureThreshold: 3
            
            startup:
              enabled: true
              type: HTTP
              spec:
                httpGet:
                  path: /health
                  port: 8096
                initialDelaySeconds: 10
                periodSeconds: 5
                timeoutSeconds: 3
                failureThreshold: 30

      # Pod-level security context
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

  service:
    main:
      enabled: true
      primary: true
      type: ClusterIP
      controller: main
      ports:
        http:
          enabled: true
          primary: true
          port: 8096
          protocol: HTTP
          targetPort: 8096

  ingress:
    main:
      enabled: false

  persistence:
    config:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/config/jellyfin"
      globalMounts:
        - path: /config
          readOnly: false
    
    media:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/media"
      globalMounts:
        - path: /media
          readOnly: true
    
    cache:
      enabled: true
      type: nfs
      server: "192.168.0.5"
      path: "/mnt/storage/cache/jellyfin"
      globalMounts:
        - path: /cache
          readOnly: false
    
virtualService:
  enabled: true
  name: "jellyfin-virtualservice"
  host: "jellyfin.home.lan"
  gateway: "istio-system/istio-ingressgateway"
  prefix: "/"
  service:
    host: "jellyfin.jellyfin.svc.cluster.local"
    port: 8096
  timeout: "300s"
  retries:
    attempts: 2
    perTryTimeout: "2s"
