apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr-route
  namespace: radarr
spec:
  parentRefs:
    - name: main-gateway
      namespace: kube-system
  hostnames:
    - "radarr.homelab"
  rules:
    - backendRefs:
        - name: radarr
          port: 80
