apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr-route
  namespace: sonarr
spec:
  parentRefs:
    - name: main-gateway
      namespace: kube-system
  hostnames:
    - "sonarr.homelab"
  rules:
    - backendRefs:
        - name: sonarr
          port: 80
