apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: ingress-nginx  # Do not set in case it overrides resources needed in kube-system
resources:
  - namespace.yaml
  - priorityclass.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.9.1
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true
    valuesFile: values.yaml
