apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  namespace: infrastructure
  version: 0.1.0
  valuesFile: values.yaml
