apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ac-worldserver
spec:
  interval: 30m
  dependsOn:
    - name: ac-database
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      main:
        enabled: true
        type: statefulset
        replicas: 1
        initContainers:
          init-playerbots-modules:
            image:
              repository: ghcr.io/woobay/ac-wotlk-playerbots-dbimport
              tag: "core-3adbe20_module-64f14c3_mbbridge-759c100_ahbot-9fbcbe6_ixp-0de806c"
            command: ["sh", "-c"]
            args:
              - "cp -r /azerothcore/modules/. /playerbots-modules-seed/"
        containers:
          main:
            stdin: true
            tty: true
            image:
              repository: ghcr.io/woobay/ac-wotlk-playerbots-worldserver
              tag: "core-3adbe20_module-64f14c3_mbbridge-759c100_ahbot-9fbcbe6_ixp-0de806c"
              pullPolicy: IfNotPresent
            env:
              AC_LOGIN_DATABASE_INFO:
                valueFrom:
                  secretKeyRef:
                    name: ac-database-secret
                    key: AC_LOGIN_DATABASE_INFO
              AC_WORLD_DATABASE_INFO:
                valueFrom:
                  secretKeyRef:
                    name: ac-database-secret
                    key: AC_WORLD_DATABASE_INFO
              AC_CHARACTER_DATABASE_INFO:
                valueFrom:
                  secretKeyRef:
                    name: ac-database-secret
                    key: AC_CHARACTER_DATABASE_INFO
              AC_PLAYERBOTS_DATABASE_INFO:
                valueFrom:
                  secretKeyRef:
                    name: ac-database-secret
                    key: AC_PLAYERBOTS_DATABASE_INFO
              AC_UPDATES_ENABLE_DATABASES: "7"
              AC_PLAYERBOTS_UPDATES_ENABLE_DATABASES: "1"
              AC_DATA_DIR: "/azerothcore/env/dist/data"
              AC_MAP_UPDATE_THREADS: "2"
              AC_RATE_XP_KILL: "3"
              AC_RATE_XP_QUEST: "3"
              AC_RATE_XP_EXPLORE: "3"
              AC_RATE_DROP_MONEY: "3"
              AC_RATE_DROP_ITEM_NORMAL: "2"
              AC_RATE_DROP_ITEM_RARE: "2"
              AC_RATE_DROP_ITEM_EPIC: "1.5"
              AC_RATE_REPUTATION_GAIN: "2"
              AC_SKILL_GAIN_CRAFTING: "2"
              AC_SKILL_GAIN_GATHERING: "2"
              AC_INDIVIDUAL_XP_ENABLED: "1"
              AC_INDIVIDUAL_XP_ANNOUNCE: "1"
              AC_INDIVIDUAL_XP_ANNOUNCE_RATES_ON_LOGIN: "1"
              AC_INDIVIDUAL_XP_MAX_XP_RATE: "3"
              AC_INDIVIDUAL_XP_DEFAULT_XP_RATE: "1"
              AC_PLAYERBOTS_DATABASE_WORKER_THREADS: "1"
              AC_PLAYERBOTS_DATABASE_SYNCH_THREADS: "1"
              AC_AI_PLAYERBOT_ENABLED: "1"
              AC_AI_PLAYERBOT_RANDOM_BOT_AUTOLOGIN: "1"
              AC_AI_PLAYERBOT_DISABLED_WITHOUT_REAL_PLAYER: "1"
              AC_AI_PLAYERBOT_DISABLED_WITHOUT_REAL_PLAYER_LOGIN_DELAY: "30"
              AC_AI_PLAYERBOT_DISABLED_WITHOUT_REAL_PLAYER_LOGOUT_DELAY: "300"
              AC_AI_PLAYERBOT_MIN_RANDOM_BOTS: "100"
              AC_AI_PLAYERBOT_MAX_RANDOM_BOTS: "200"
              AC_AI_PLAYERBOT_RANDOM_BOT_ACCOUNT_PREFIX: "rndbot"
              AC_AI_PLAYERBOT_BOT_ACTIVE_ALONE: "10"
              AC_AI_PLAYERBOT_BOT_ACTIVE_ALONE_SMART_SCALE: "1"
              AC_AI_PLAYERBOT_BOT_ACTIVE_ALONE_SMART_SCALE_WHEN_MIN_LEVEL: "1"
              AC_AI_PLAYERBOT_BOT_ACTIVE_ALONE_SMART_SCALE_WHEN_MAX_LEVEL: "80"
              AC_AI_PLAYERBOT_SYNC_LEVEL_WITH_PLAYERS: "1"
              AC_AI_PLAYERBOT_RANDOM_BOT_CONCENTRATE_IN_PLAYER_ZONE: "1"
              AC_AI_PLAYERBOT_LEVEL_BRACKETS_ENABLED: "1"
              AC_AI_PLAYERBOT_LEVEL_BRACKETS_DYNAMIC_USE_DYNAMIC_DISTRIBUTION: "1"
              AC_AI_PLAYERBOT_LEVEL_BRACKETS_DYNAMIC_REAL_PLAYER_WEIGHT: "3.0"
            resources:
              requests: {cpu: 250m, memory: 1Gi}
              limits: {cpu: 3000m, memory: 8Gi}
            probes:
              liveness:
                enabled: true
                type: TCP
                spec:
                  initialDelaySeconds: 60
                  periodSeconds: 15
              readiness:
                enabled: true
                type: TCP
                spec:
                  initialDelaySeconds: 45
                  periodSeconds: 10
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 3001
            fsGroup: 3001
    service:
      main:
        enabled: true
        primary: true
        controller: main
        ports:
          world:
            enabled: true
            primary: true
            port: 8085
          soap:
            enabled: true
            port: 7878
    persistence:
      client-data:
        enabled: true
        type: nfs
        server: "192.168.20.5"
        path: "/mnt/storage/config/wow-client-data"
        globalMounts:
          - path: /azerothcore/env/dist/data
            readOnly: true
      playerbots-modules:
        type: emptyDir
        advancedMounts:
          main:
            init-playerbots-modules:
              - path: /playerbots-modules-seed
            main:
              - path: /azerothcore/modules
