apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
resources:
  - ./helmrelease.yaml
  - ./tcproute.yaml
configMapGenerator:
  - name: ac-worldserver-playerbots-conf
    files:
      - playerbots.conf=./resources/playerbots.conf
generatorOptions:
  disableNameSuffixHash: true
