apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ac-worldserver
spec:
  interval: 30m
  dependsOn:
    - name: ac-database
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      main:
        enabled: true
        type: statefulset
        replicas: 1
        containers:
          main:
            image:
              repository: acore/ac-wotlk-worldserver
              tag: "14.0.0-dev"
              pullPolicy: IfNotPresent
            env:
              AC_LOGIN_DATABASE_INFO: "ac-database;3306;root;changeme-strong-password;acore_auth"
              AC_WORLD_DATABASE_INFO: "ac-database;3306;root;changeme-strong-password;acore_world"
              AC_CHARACTER_DATABASE_INFO: "ac-database;3306;root;changeme-strong-password;acore_characters"
            resources:
              requests: {cpu: 500m, memory: 2Gi}
              limits: {cpu: 4000m, memory: 6Gi}
            probes:
              liveness:
                enabled: true
                type: TCP
                spec:
                  initialDelaySeconds: 60
                  periodSeconds: 15
              readiness:
                enabled: true
                type: TCP
                spec:
                  initialDelaySeconds: 45
                  periodSeconds: 10
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 3001
            fsGroup: 3001
    service:
      main:
        enabled: true
        primary: true
        controller: main
        ports:
          world:
            enabled: true
            primary: true
            port: 8085
          soap:
            enabled: true
            port: 7878
    route:
      main:
        enabled: true
        kind: TCPRoute
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: wow-world
        rules:
          - backendRefs:
              - identifier: main
                port: 8085
    persistence:
      client-data:
        enabled: true
        type: nfs
        server: "192.168.20.5"
        path: "/mnt/storage/config/wow-client-data"
        globalMounts:
          - path: /azerothcore/env/dist/data
            readOnly: true
