{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.virtualService.host | quote }}
  gateways:
  - {{ .Values.virtualService.gateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.prefix | quote }}
      headers:
        # Explicit WebSocket upgrade headers
        connection:
          exact: "upgrade"
        upgrade:
          exact: "websocket"
    route:
    - destination:
        host: {{ .Values.virtualService.service.host }}
        port:
          number: {{ .Values.virtualService.service.port }}
    timeout: {{ .Values.virtualService.timeout }}

  - route:  # Regular HTTP traffic
    - destination:
        host: {{ .Values.virtualService.service.host }}
        port:
          number: {{ .Values.virtualService.service.port }}
    retries:
      attempts: {{ .Values.virtualService.retries.attempts }}
      perTryTimeout: {{ .Values.virtualService.retries.perTryTimeout }}
    timeout: {{ .Values.virtualService.timeout }}
{{- end }}
